package com.zchess.service;

import org.springframework.stereotype.Service;

@Service
public class ChessService {

    /* =========================
           MOVE VALIDATION ENTRY
               ========================= */

                   public boolean tryMove(String[] board, int from, int to, String turn) {

                           String piece = board[from];
                                   if(piece.equals(".")) return false;

                                           if(!piece.startsWith(turn.substring(0,1))) return false;

                                                   if(!isValidPieceMove(board, from, to, piece)) return false;

                                                           // simulate move
                                                                   String captured = board[to];
                                                                           board[to] = piece;
                                                                                   board[from] = ".";

                                                                                           if(isKingInCheck(board, turn)){
                                                                                                       board[from] = piece;
                                                                                                                   board[to] = captured;
                                                                                                                               return false;
                                                                                                                                       }

                                                                                                                                               return true;
                                                                                                                                                   }

                                                                                                                                                       /* =========================
                                                                                                                                                              PIECE MOVE RULES
                                                                                                                                                                  ========================= */

                                                                                                                                                                      private boolean isValidPieceMove(String[] b, int f, int t, String p){
                                                                                                                                                                              int fr=f/8, fc=f%8;
                                                                                                                                                                                      int tr=t/8, tc=t%8;

                                                                                                                                                                                              switch(p.substring(1)){
                                                                                                                                                                                                          case "p": return pawn(b,f,t,p);
                                                                                                                                                                                                                      case "r": return rook(b,f,t);
                                                                                                                                                                                                                                  case "n": return knight(fr,fc,tr,tc);
                                                                                                                                                                                                                                              case "b": return bishop(b,f,t);
                                                                                                                                                                                                                                                          case "q": return rook(b,f,t) || bishop(b,f,t);
                                                                                                                                                                                                                                                                      case "k": return king(fr,fc,tr,tc);
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                              private boolean pawn(String[] b,int f,int t,String p){
                                                                                                                                                                                                                                                                                                      int dir=p.startsWith("w")?-8:8;
                                                                                                                                                                                                                                                                                                              if(t==f+dir && b[t].equals(".")) return true;
                                                                                                                                                                                                                                                                                                                      if(Math.abs((t%8)-(f%8))==1 && t==f+dir && !b[t].equals(".")) return true;
                                                                                                                                                                                                                                                                                                                              return false;
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                      private boolean rook(String[] b,int f,int t){
                                                                                                                                                                                                                                                                                                                                              if(f/8!=t/8 && f%8!=t%8) return false;
                                                                                                                                                                                                                                                                                                                                                      int step=(t>f)?1:-1;
                                                                                                                                                                                                                                                                                                                                                              if(f%8==t%8) step=(t>f)?8:-8;
                                                                                                                                                                                                                                                                                                                                                                      for(int i=f+step;i!=t;i+=step)
                                                                                                                                                                                                                                                                                                                                                                                  if(!b[i].equals(".")) return false;
                                                                                                                                                                                                                                                                                                                                                                                          return true;
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                  private boolean bishop(String[] b,int f,int t){
                                                                                                                                                                                                                                                                                                                                                                                                          int df=Math.abs((f/8)-(t/8));
                                                                                                                                                                                                                                                                                                                                                                                                                  int dc=Math.abs((f%8)-(t%8));
                                                                                                                                                                                                                                                                                                                                                                                                                          if(df!=dc) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                  int step=(t>f)?9:-9;
                                                                                                                                                                                                                                                                                                                                                                                                                                          if((t%8)<(f%8)) step=(t>f)?7:-7;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  for(int i=f+step;i!=t;i+=step)
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(!b[i].equals(".")) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              private boolean knight(int fr,int fc,int tr,int tc){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      int dr=Math.abs(fr-tr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              int dc=Math.abs(fc-tc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return dr*dc==2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              private boolean king(int fr,int fc,int tr,int tc){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Math.max(Math.abs(fr-tr),Math.abs(fc-tc))==1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     CHECK DETECTION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ========================= */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             public boolean isKingInCheck(String[] board,String turn){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     String king=turn.equals("white")?"wk":"bk";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             int kingPos=-1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     for(int i=0;i<64;i++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if(board[i].equals(king))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 kingPos=i;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         String enemy=turn.equals("white")?"b":"w";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for(int i=0;i<64;i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if(board[i].startsWith(enemy)){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if(isValidPieceMove(board,i,kingPos,board[i]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     /* =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CHECKMATE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ========================= */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public boolean isCheckmate(String[] board,String turn){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!isKingInCheck(board,turn)) return false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for(int i=0;i<64;i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(board[i].startsWith(turn.substring(0,1))){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for(int j=0;j<64;j++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    String[] copy=board.clone();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(tryMove(copy,i,j,turn))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }