package com.zchess.service;

import org.springframework.stereotype.Service;

@Service
public class ChessService {

    // ===============================
        // MOVE VALIDATION
            // ===============================
                public boolean isValidMove(String[] board, int from, int to, String turn) {

                        String piece = board[from];
                                if (piece.equals(".")) return false;

                                        if (turn.equals("white") && !piece.startsWith("w")) return false;
                                                if (turn.equals("black") && !piece.startsWith("b")) return false;

                                                        String target = board[to];
                                                                if (!target.equals(".") && target.charAt(0) == piece.charAt(0))
                                                                            return false;

                                                                                    int fr = from / 8;
                                                                                            int fc = from % 8;
                                                                                                    int tr = to / 8;
                                                                                                            int tc = to % 8;

                                                                                                                    char p = piece.charAt(1);

                                                                                                                            // PAWN
                                                                                                                                    if (p == 'p') {
                                                                                                                                                if (piece.startsWith("w")) {
                                                                                                                                                                if (fc == tc && board[to].equals(".") && tr == fr - 1) return true;
                                                                                                                                                                                if (fr == 6 && fc == tc && tr == 4 && board[to].equals(".")) return true;
                                                                                                                                                                                                if (Math.abs(tc - fc) == 1 && tr == fr - 1 && !board[to].equals(".")) return true;
                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                            if (fc == tc && board[to].equals(".") && tr == fr + 1) return true;
                                                                                                                                                                                                                                            if (fr == 1 && fc == tc && tr == 3 && board[to].equals(".")) return true;
                                                                                                                                                                                                                                                            if (Math.abs(tc - fc) == 1 && tr == fr + 1 && !board[to].equals(".")) return true;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                    // ROOK
                                                                                                                                                                                                                                                                                                            if (p == 'r') {
                                                                                                                                                                                                                                                                                                                        return fr == tr || fc == tc;
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                        // KNIGHT
                                                                                                                                                                                                                                                                                                                                                if (p == 'n') {
                                                                                                                                                                                                                                                                                                                                                            int dr = Math.abs(fr - tr);
                                                                                                                                                                                                                                                                                                                                                                        int dc = Math.abs(fc - tc);
                                                                                                                                                                                                                                                                                                                                                                                    return (dr == 2 && dc == 1) || (dr == 1 && dc == 2);
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    // BISHOP
                                                                                                                                                                                                                                                                                                                                                                                                            if (p == 'b') {
                                                                                                                                                                                                                                                                                                                                                                                                                        return Math.abs(fr - tr) == Math.abs(fc - tc);
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        // QUEEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (p == 'q') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return fr == tr || fc == tc ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Math.abs(fr - tr) == Math.abs(fc - tc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // KING
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (p == 'k') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return Math.abs(fr - tr) <= 1 && Math.abs(fc - tc) <= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // CHECK DETECTION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       public boolean isKingInCheck(String[] board, String turn) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               String king = turn.equals("white") ? "wk" : "bk";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       int kingPos = -1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               for (int i = 0; i < 64; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (board[i].equals(king)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           kingPos = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (kingPos == -1) return false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               String opponent = turn.equals("white") ? "black" : "white";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       for (int i = 0; i < 64; i++) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   String piece = board[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (piece.equals(".")) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (opponent.equals("white") && piece.startsWith("w")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (isValidMove(board, i, kingPos, "white"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (opponent.equals("black") && piece.startsWith("b")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (isValidMove(board, i, kingPos, "black"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }