package com.zchess.service;

import com.zchess.engine.Board;
import com.zchess.engine.MoveValidator;
import com.zchess.engine.GameState;
import com.zchess.engine.CheckValidator;
import com.zchess.engine.ChessNotation;
import com.zchess.entity.Move;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class MoveService {

    private static List<String> history = new ArrayList<>();
        private static List<Move> moves = new ArrayList<>();


            public String[][] getBoard(){
                    return Board.getBoard();
                        }


                            public List<String> getHistory(){
                                    return history;
                                        }


                                            public String getTurn(){
                                                    return GameState.currentTurn;
                                                        }


                                                            public String[][] move(Move move){

                                                                    String[][] board = Board.getBoard();

                                                                            int fr = move.getFromRow();
                                                                                    int fc = move.getFromCol();
                                                                                            int tr = move.getToRow();
                                                                                                    int tc = move.getToCol();

                                                                                                            String piece = board[fr][fc];

                                                                                                                    if(piece == null)
                                                                                                                                return board;

                                                                                                                                        boolean isWhite = piece.startsWith("w");

                                                                                                                                                if(isWhite && !GameState.currentTurn.equals("white"))
                                                                                                                                                            return board;

                                                                                                                                                                    if(!isWhite && !GameState.currentTurn.equals("black"))
                                                                                                                                                                                return board;

                                                                                                                                                                                        boolean valid =
                                                                                                                                                                                                        MoveValidator.isValidMove(
                                                                                                                                                                                                                                piece,
                                                                                                                                                                                                                                                        fr,
                                                                                                                                                                                                                                                                                fc,
                                                                                                                                                                                                                                                                                                        tr,
                                                                                                                                                                                                                                                                                                                                tc,
                                                                                                                                                                                                                                                                                                                                                        board
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                if(!valid)
                                                                                                                                                                                                                                                                                                                                                                                            return board;

                                                                                                                                                                                                                                                                                                                                                                                                    String captured = board[tr][tc];

                                                                                                                                                                                                                                                                                                                                                                                                            board[tr][tc] = piece;
                                                                                                                                                                                                                                                                                                                                                                                                                    board[fr][fc] = null;

                                                                                                                                                                                                                                                                                                                                                                                                                            boolean kingSafe =
                                                                                                                                                                                                                                                                                                                                                                                                                                            !CheckValidator.isKingInCheck(board,isWhite);

                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(!kingSafe){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                board[fr][fc] = piece;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            board[tr][tc] = captured;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return board;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        move.setPiece(piece);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                moves.add(move);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ✔ FIXED CAPTURE VARIABLE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boolean capture = captured != null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.add(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ChessNotation.convert(piece,fr,fc,tr,tc,capture)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        switchTurn();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return board;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void undo(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(moves.isEmpty())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    moves.remove(moves.size()-1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!history.isEmpty())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.remove(history.size()-1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Board.resetBoard();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        String[][] board = Board.getBoard();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for(Move m : moves){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            board[m.getToRow()][m.getToCol()] = m.getPiece();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        board[m.getFromRow()][m.getFromCol()] = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        switchTurn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public void reset(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        moves.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                history.clear();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Board.resetBoard();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GameState.currentTurn = "white";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private void switchTurn(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(GameState.currentTurn.equals("white"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            GameState.currentTurn = "black";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GameState.currentTurn = "white";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }