package com.zchess.engine;

public class MoveValidator {

    public static boolean isValidMove(String piece,
                                          int fr,
                                                                                int fc,
                                                                                                                      int tr,
                                                                                                                                                            int tc,
                                                                                                                                                                                                  String[][] board) {

                                                                                                                                                                                                          if (piece.startsWith("wp") || piece.startsWith("bp")) {
                                                                                                                                                                                                                      return PawnValidator.isValid(fr, fc, tr, tc, board);
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                      if (piece.endsWith("r")) {
                                                                                                                                                                                                                                                  return RookValidator.isValid(fr, fc, tr, tc);
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                  if (piece.endsWith("n")) {
                                                                                                                                                                                                                                                                              return KnightValidator.isValid(fr, fc, tr, tc);
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                              if (piece.endsWith("b")) {
                                                                                                                                                                                                                                                                                                          return BishopValidator.isValid(fr, fc, tr, tc);
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                          if (piece.endsWith("q")) {
                                                                                                                                                                                                                                                                                                                                      return QueenValidator.isValid(fr, fc, tr, tc);
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                      if (piece.endsWith("k")) {
                                                                                                                                                                                                                                                                                                                                                                  return KingValidator.isValid(fr, fc, tr, tc);
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      